### PR TITLE
Added dnaindia.com

### PR DESCRIPTION
**Pull request by ingenioustechie**

### CODE REVIEW

**Comment by ingenioustechie** [comment]
@HarryC145 I changed it, do I need to add another pull request ? and delete this one? 
Note: Newbie here doing pull request first time :)

**Comment by HarryC145** [comment]
You should be able to update it. I still see a refresh of 10.

**Comment by ingenioustechie** [comment]
Changed refresh time to 6 as it will be good to check it every 1 hour. 
No I'm not part the team, but would like to be part of ArchiveTeam

**Comment by HarryC145** [comment]
We would welcome you into the ArchiveTeam, drop into #archiveteam on EFnet and say Hi. One more thing before we start on that site, you need to make sure that all the pages are on the same indent level, so you need to bring all the others back in line with the first one.

**Pull request merged**
