### PR TITLE
Ready to merge

### PR DESCRIPTION
**Pull request by djsmiley2k**
All the trinity mirror group sites.

### CODE REVIEW

**Comment by DopefishJustin** [comment]
Looks good except that some of the filenames contain the hyphen character - which is not allowed and breaks the grabber for whatever reason.

**Comment by djsmiley2k** [comment]
@DopefishJustin I maybe being blind but I don't see any hyphens in file names?

**Comment by djsmiley2k** [comment]
@DopefishJustin as long as it was only web__macclesfield-express_co_uk.py then it's fixed (grep didn't find anymore...)

**Comment by DopefishJustin** [comment]
That was it, yes.

**Comment by Arkiver2** [comment]
Please replace `refresh = 8` by `refresh = 7` in web__macclesfieldexpress_co_uk.py.
Change the name of web__macclesfieldexpress_co_uk.py to web__macclesfield_express_co_uk.py, the '-' is then replaced by a '_'.

**Pull request merged**
